Oval crop corners added
CanHub/Android-Image-Cropper pull request #307
Opened 2022-01-25 10:26 UTC by bhagyae5308

The changes are related to https://github.com/CanHub/Android-Image-Cropper/issues/305

1. Added provision to add Oval crop corners when the crop style is Rectangle
2. Setters exposed to had crop corner radius and fill color

_Add the issue linked to this PR_
close #

_Please choose one of the two templates and delete this message and the other template_

# Template 1 [New Feature]
## Description:
_very small explanation about what was done_

## Check list for the Code Reviewer:
* [ ] CHANGELOG
* [ ] README
* [ ] Wiki
* [ ] Version Number

# Template 2 [Bug]
## Bug
### Cause:
_small explanation_

### Reproduce
_more detail steps better_
GIVEN:
WHEN:
THEN:

### How the bug was solved:
Small explanation

2022-01-25 11:08 UTC, Canato reviewed
Didn't finish the review yet, will give it more attention tomorrow probably, but great work =D

Thanks for this, raise some minor stuffs

2022-01-25 11:08 UTC, Canato commented on cropper/src/main/java/com/canhub/cropper/CropImageContractOptions.kt
> +    fun setCircleCornerFillColor(circleFillColor:Int):CropImageContractOptions{
Do we expect the value on RGB or Hex or Android Int? Would be nice to have some tip on the variable name, like `circleFillColorHexValue` and to have it clear on the documentation

2022-01-25 11:08 UTC, Canato commented on cropper/src/main/java/com/canhub/cropper/CropImageContractOptions.kt
> +     */
Default value?

2022-01-25 11:08 UTC, Canato commented on cropper/src/main/java/com/canhub/cropper/CropOverlayView.kt
> +            // borderPaint.isAntiAlias = true
?

2022-01-25 11:08 UTC, Canato commented on cropper/src/main/java/com/canhub/cropper/CropOverlayView.kt
> +    //ToDO:Need to add documentation
👀 you said hahahaha

2022-01-28 09:55 UTC, Canato commented
@bhagyae5308 the CI is not passing, could you take a look please?

2022-02-02 05:45 UTC, bhagyae5308 commented
@Canato Apologies for late update, I was occupied with some other tasks.

2022-02-02 09:40 UTC, Canato requested changes
No worries about the time, all work here is volunteer you are already adding great value to the lib! and i'm thankful for this!

Now I had time to check with more attention ^^

1. We need to update the CHANGELOG

Almost ready to go 🎉

2022-02-02 09:40 UTC, Canato commented on cropper/src/main/java/com/canhub/cropper/CropImageContractOptions.kt
> +     * @param circleFillColorHexValue Hex value of the color (Default is MAGENTA)
Let's change the default to White please

2022-02-02 09:40 UTC, Canato commented on cropper/src/main/java/com/canhub/cropper/CropOverlayView.kt
> +        mBorderCornerPaint = getNewPaintOrNull(mOptions?.borderCornerThickness ?: 0.0f, mOptions?.borderCornerColor ?: Color.WHITE)
Cool

2022-02-02 09:40 UTC, Canato commented on sample/src/main/res/layout/fragment_options.xml
> +                android:visibility="gone"/>
Nice touch. Can see you are a detailed dev, thanks for it

2022-02-02 12:15 UTC, bhagyae5308 commented on cropper/src/main/java/com/canhub/cropper/CropOverlayView.kt
>              (rect.top - cornerExtension),
Added this change to align properly the corners over the edges of the rectangle. Observed this while checking it for smaller radius.

2022-02-02 12:53 UTC, Canato approved these changes

2022-02-02 12:54 UTC, merged