Add support for ScaleType.CENTER_CROP
CanHub/Android-Image-Cropper pull request #322
Opened 2022-03-03 15:38 UTC by scana

Adds support for `ScaleType.CENTER_CROP` flag - previously this would be ignored and would leave some space on either side of the view.

Closes https://github.com/CanHub/Android-Image-Cropper/issues/220

I would appreciate you testing this on your side @Canato, @PiotrBandurski - this helps with our use-case but the chance is that it breakes somebody elses.

2022-03-04 10:39 UTC, scana commented
@Canato done :)

2022-03-04 12:24 UTC, Canato requested changes
Hey @scana doing some tests when I change the `ScaleType` on the sample app it look strange

Video to explain:

https://user-images.githubusercontent.com/15942449/156762981-da21d625-5eb1-40e9-adc4-d57cdc927b0f.mp4

2022-03-04 12:34 UTC, scana commented
That's what I meant with our use-case working fine 🙃  - thank you for the video, I'll take a closer look as soon as possible (and test it with the sample app this time)

2022-03-05 17:00 UTC, scana commented
Hey @Canato just wanted to double-check with you - I've run the sample app off the `main` branch and got the exact same results you got. 

After I switch to my branch/PR however I get this (seems ok 🤔 ):

https://user-images.githubusercontent.com/1139325/156892823-4a850679-1f2c-487e-a037-226b0a48591f.mp4

2022-03-07 09:05 UTC, Canato commented
> Hey @Canato just wanted to double-check with you - I've run the sample app off the `main` branch and got the exact same results you got.
> 
> After I switch to my branch/PR however I get this (seems ok 🤔 ):
> 

oohhh no =|
We may have a bug on Main... will test a little more later today and if is the case merge this PR and open a new bug issue

2022-03-07 20:40 UTC, merged