Sample: Use 2:1 aspect ratio as 4:3 is the same as 16:9
CanHub/Android-Image-Cropper pull request #386
Opened 2022-06-16 11:20 UTC by vanniktech

Also the previous code did things different than the text shown in the UI

2022-06-17 10:14 UTC, Canato commented
We can add a new ratio, but `4:3` differ from `16:9`
![ratio](https://user-images.githubusercontent.com/15942449/174278631-807278c6-b4b3-453f-a853-97e9407d12f3.png)

2022-06-17 10:15 UTC, Canato requested changes

2022-06-17 10:15 UTC, Canato commented on sample/src/main/java/com/canhub/cropper/sample/options_dialog/SampleOptionsBottomSheet.kt
> +            Pair(2, 1) -> binding.ratio.chipTwoOne.isChecked = true
We can add a new one, but let's not remove `4:3`

2022-06-17 10:41 UTC, Canato commented
On another note, we need to update the CHANGELOG

2022-06-17 10:42 UTC, vanniktech commented
> On another note, we need to update the CHANGELOG

With what?

2022-06-17 11:28 UTC, Canato commented
> > On another note, we need to update the CHANGELOG
> 
> With what?

Add ratio `2,1`

2022-06-17 12:31 UTC, vanniktech commented
Will do once the other PR is merged, otherwise I get conflicts in the changelog file

2022-06-17 15:09 UTC, Canato approved these changes

2022-06-17 15:10 UTC, Canato requested changes
Some merge conflicts. Request changes so you get notify

2022-06-18 09:30 UTC, Canato approved these changes

2022-06-18 09:30 UTC, merged